#!/bin/bash

# remember to call "./addapps .getver" after version modifications!
VERSION="0.0.2"
IAM="2facli"
####################################################################################
check_dependencies() {
  local missing=0
  local addapps="crypter"
  local aptpkg="oathtool gocryptfs"
  local list="$addapps $aptpkg"
  addapps=" $addapps "
  for i in $list ; do
    if ! command -v $i &> /dev/null ; then
      missing=1  
      if [[ $addapps == *" $i "* ]]; then
         echo "error: $i could not be found. Install it with: addapps install $i"
      else
         echo "error: $i could not be found. Install it with: sudo apt-get install -y $i"
      fi
    fi
  done
  if [ "$missing" = "1" ] ; then
    exit 1
  fi
}
####################################################################################


show_help()
{
  echo ""
  echo "usage: $IAM init|list|create|read"
  echo ""
  echo "example:"
  echo ""
  echo "$IAM ./hugo  # create directory and a template installer script."
  echo ""
  echo "# copy desired content to the ./hugo directory and modify installer script:"
  echo "vi ./hugo/installer"
  echo ""
  echo "$IAM ./hugo # re-create installable selfextractor file: ./hugo.sh"
  echo "#or:"
  echo "$IAM ./hugo /tmp/my-selfextractor.sh"
  echo ""
}
####################################################################################
# magic main
####################################################################################

check_dependencies

options=$(getopt -l "help,version" -o "hvp:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help) 
    show_help
    exit 0
    ;;
  -v|--version) 
    echo "$VERSION"
    exit 0
    ;;
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done

if [ "$1" = "" ] ; then
  show_help
  exit 0
fi
CMD="$1"
CRYPT_AREA="2facli"

if [ ! -f ~/.config/addapps/crypter/${CRYPT_AREA}.conf ] ; then
  echo "# error: crypter AREA=${CRYPT_AREA} does not exist, create it with:"
  echo "crypter ${CRYPT_AREA} init"
  exit 1
fi
#echo '2fas() { oathtool -b --totp $( gpg -q -d ~/.config/2fas/${1}) ; }' >> .bash_aliases
#echo "<paste-paring-key-here>" | sed -e "s/ //g" | gpg -c > ~/.config/2fas/rda
#gpg -q -d ~/.config/2fas/rda



exit 0

