#!/bin/bash
VERSION="0.11.13"

ARCH=$(dpkg --print-architecture)
ALT_ARCH0="x86_64"
ALT_ARCH1="x86_64"
if [ "${ARCH}" = "arm64" ] ; then
  ALT_ARCH0="aarch64"
  ALT_ARCH1="arm64"
fi
# a..app; i..installer
list="
a;addapps;additional apps;$VERSION;--version;https://mde.gate-7.de/addapps/addapps
a;selfextractor;selfextractor;0.0.2;--version;https://mde.gate-7.de/addapps/selfextractor
a;md-exec;execute md code sections;1.0.2;--version;https://raw.githubusercontent.com/unimock/addapps/main/md-exec
a;sshenc;ssh encryption;0.0.0;--version;https://mde.gate-7.de/addapps/sshenc
a;2facli;2FA CLI;0.0.2;--version;https://mde.gate-7.de/addapps/2facli
a;wg-cert-mgr;my wg cert manager;0.9.0;--version;https://mde.gate-7.de/addapps/wg-cert-mgr
a;crypter;gocryprt CLI;1.0.5;--version;https://mde.gate-7.de/addapps/crypter
a;print-emojis;emojis on console example;0.0.2;--version;https://mde.gate-7.de/addapps/print-emojis
a;stsync;syncting stc CLI;0.0.6;--version;https://mde.gate-7.de/addapps/stsync
a;difft;difftastic;0.65.0;--version;https://github.com/Wilfred/difftastic/releases/download/<VERSION>/difft-${ALT_ARCH0}-unknown-linux-gnu.tar.gz
a;yq;yaml processor;4.48.1;--version;https://github.com/mikefarah/yq/releases/download/v<VERSION>/yq_linux_${ARCH}
a;stc;syncthing CLI;;;https://github.com/tenox7/stc/releases/download/1.5.4/stc-${ARCH}-linux
a;mc;minio CLI;;;https://dl.min.io/client/mc/release/linux-${ARCH}/mc
a;hcloud;Hetzner-Cloud CLI;1.55.0;version;https://github.com/hetznercloud/cli/releases/download/v<VERSION>/hcloud-linux-${ARCH}.tar.gz
a;http-here;http-here;;;https://github.com/western/http-here/releases/download/v1.14.5/http-here.gz
i;mde-env;mde-base installer;0.0.3;--version;https://mde.gate-7.de/addapps/mde-env
i;dc-env;dc installer;1.20.0;--version;https://mde.gate-7.de/addapps/dc-env
"
####################################################################################
addapps_spinner() {
  type=$1         # type 1..13
  interval=$2     # interval 0.25
  pid=$3
  msg="$4"
  case "$type" in
  1)  frame=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏") ;;
  2)  frame=("-" "\\" "|" "/") ;;
  3)  frame=("🌑" "🌒" "🌓" "🌔" "🌕" "🌖"  "🌗" "🌘") ;;
  4)  frame=("◐" "◓" "◑" "◒") ;;
  5)  frame=("◇" "◈" "◆") ;;
  6)  frame=("⚬" "⚭" "⚮" "⚯") ;;
  7)  frame=("░" "▒" "▓" "█" "▓" "▒") ;;
  8) frame=("☉" "◎" "◉" "●" "◉") ;;
  9) frame=("❤" "♥" "♡") ;;
  10) frame=("✧" "☆" "★" "✪" "◌" "✲") ;;
  11) frame=("●" "◕" "☯" "◔" "◕") ;;

  esac
  #https://github.com/lnfnunes/bash-progress-indicator.git
  trap "{ tput cnorm ; exit 1 ; }" SIGINT SIGTERM
  console=0
  if [ -t 1 ]; then
    console=1
    tput civis # cursor invisible
  else
    echo "START: $msg ..."
  fi
  while ps -p $pid &>/dev/null; do
    if [ "$console" = "1" ] ; then
      echo -ne "\\r  $msg ..."
      for k in "${!frame[@]}"; do
        echo -ne "\\r${frame[k]}"
        sleep $interval
      done
    else
      sleep $interval
    fi   
  done
  wait $pid
  ret=$?
  end="✔"
  alt="OK:   "
  if [ "$ret" != "0" ] ; then
     end="❌"
     alt="ERR:  "
  fi
  if [ "$console" = "1" ] ; then
    echo -ne "\\r${end} $msg\\n"
    tput cnorm  # cursor normal
  else
    echo "${alt} $msg"
  fi
  trap - SIGINT SIGTERM # Disable the trap      
  return $ret
}
####################################################################################
_install() {
  list_type="$1"
  name="$2"
  url="$3"

  FI=$(mktemp)
  (wget -q -O $FI $url) &
  pid=$!
  addapps_spinner 1 0.25 $pid "installing $name"
  if [ -f /usr/local/bin/${name} ] ; then
    sudo rm -f /usr/local/bin/.addapps-${name}
    sudo mv /usr/local/bin/${name} /usr/local/bin/.addapps-${name}
  fi
  if [[ $url == *".tar.gz" ]] ; then
    sudo tar -C /usr/local/bin/ -xzf $FI
  elif [[ $url == *".gz"  ]] ; then
    cat $FI | gunzip | sudo tee /usr/local/bin/$name >/dev/null
  else
    sudo cp $FI /usr/local/bin/$name
  fi
  sudo chmod 755 /usr/local/bin/$name
  sudo chown root:root /usr/local/bin/$name
  if [ "$name" = "addapps" ] ; then
    x=$( mktemp )
    cat /usr/local/bin/$name | sed  -e '/^addapps_spinner()/,/^}$/!d' > $x
    if [ ! -d  /usr/local/include ] ; then
      sudo mkdir -p /usr/local/include
    fi
    sudo cp $x /usr/local/include/addapps.funcs
    sudo chmod 644  /usr/local/include/addapps.funcs
    rm $x
  fi
  rm $FI

  if [ "$list_type" = "i" ] ; then # installer script
    /usr/local/bin/${name} install
  fi
}
####################################################################################
_remove() {
  list_type="$1"
  name="$2"
  if [ -f /usr/local/bin/${name} ] ; then
    if [ "$list_type" = "i" ] ; then # installer script
      /usr/local/bin/$name remove
    fi
    sudo rm -f /usr/local/bin/.addapps-${name}
    sudo mv    /usr/local/bin/${name} /usr/local/bin/.addapps-${name}
    (sleep 0.1) &
    addapps_spinner 1 0.1 $! "removing $name"
  fi
}
####################################################################################
show_help() {
  if [ "$1" = "" ] ; then
    echo ""
    echo "usage: $(basename $0) [-v|--version|-h|--help] refresh|update|ls|install|remove [<application>]"
    echo ""
    echo "examples:"
    echo ""
    echo "$IAM ls [--installed|--updatable] [--short]  # list and show version of [installed] additional applications"
    echo "$IAM refresh           # refresh application versions from addapp store"
    echo "$IAM update            # update all outdeted applications"
    echo "$IAM install <package> # installs or update an application"
    echo "$IAM remove  <package> # uninstall an application"
    echo ""
    echo "$IAM .getver           # pre-commit fetch versions"
    echo ""
    exit 0
  fi
}

####################################################################################
# magic main
####################################################################################

if [[ "$1" == "" ]] ; then
  show_help
  exit 0
fi
short=0
only_installed=0
only_updatable=0
options=$(getopt -l "help,version,installed,short,updatable" -o "hvps:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help) 
    show_help
    exit 0
    ;;
  -v|--version) 
    echo "$VERSION"
    exit 0
    ;;
  --installed)
    only_installed=1
    ;;
  --updatable)
    only_updatable=1
    ;;
  -s|--short)
    short=1
    ;;
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done
ls_ret=0
update_done="0"
if [[ "$short" == "0" && "$1" != "refresh" ]] ; then
  MASK="|%-1s|%-15s|%-8s|%-8s|%-25s|\n"
  printf "$MASK" "  " "application" "version" "latest" "description"
  printf "$MASK" "--" "---------------" "--------" "--------" "-------------------------"
fi
while read -r i ; do
  list_type=$( echo "$i"     | cut -d";" -f1)
  name=$( echo "$i"     | cut -d";" -f2)
  bez=$(  echo "$i"     | cut -d";" -f3)
  ver=$(  echo "$i"     | cut -d";" -f4)
  ver_cmd=$(  echo "$i" | cut -d";" -f5)
  url=$(  echo "$i"     | cut -d";" -f6 | sed -e "s/<VERSION>/$ver/g")
  if [ "$name" = "" ] ; then continue ; fi
  state="⬜"
  version=""
  installed=0
  updatable=0
  if [ -e /usr/local/bin/$name ] ; then
    state="✅"
    installed=1
    if [ "$ver_cmd" != "" ] ; then
      version=$( /usr/local/bin/$name $ver_cmd 2>/dev/null | head -n1 | sed -e "s/(.*)//g" | grep -o '[0-9,.]*' )
      if [[ "$version" == "" ]] ; then
        state="💡"
        installed=1
        ls_ret=255  # warn
      elif [[ "$version" != "$ver" ]] ; then
        state="☑ "
        installed=1
        updatable=1
        if [[ "$1" == "ls" ]] ; then
          if [[ "${ls_ret}" == "0" ]] ; then
            ls_ret=254 # update
          fi
        elif [[ "$1" == "update" ]] ; then
          if [[ "$2" == "" ||  "$2" == "$name" ]] ; then
            _install "$list_type" "$name" "$url"
            update_done="1"
          fi
        fi
      fi
    fi
  fi
  if [[ "$1" == "ls" ]] ; then
    if [[ ( "$only_installed" == "0" && "$only_updatable" == "0" ) || \
          ( "$only_installed" == "1" && "$installed" == "1" )      || \
          ( "$only_updatable" == "1" && "$updatable" == "1" )   ]] ; then
      if [ "$short" = "0" ] ; then
        printf "$MASK" "$state" "$name" "$version" "$ver" "$bez"
      else
        printf "%s\n" "$name"
      fi
    fi
  fi
  if [[ "$1" == "refresh" && "$name" == "addapps"  ]] ; then
    _install "$list_type" "$name" "$url"
    #echo ""
    #$0 ls
    exit $?
  fi
  if [[ "$1" == "install" && "$2" == "$name" ]] ; then
    _install "$list_type" "$name" "$url"
    exit 0
  fi
 
  if [[ "$1" == "remove" && "$2" == "$name" ]] ; then
    _remove "$list_type" "$name"
    exit 0
  fi
  if [[ "$1" == ".getver" && "$name" != "addapps" ]] ; then
    if [ -f ./$name ] ; then
      if [ "$name" = "dc-env" ] ; then
        VERSION=$(cat /opt/dc/VERSION)
      else
        eval $(grep "^VERSION=" ./$name 2>/dev/null)
      fi
      echo "$name : $ver -> $VERSION"
      sed -i "/^.;${name};/s/$ver/$VERSION/g" ./addapps
    fi
  fi
done <<< "$(echo "$list")"
if [[ "$1" == "ls" ]] ; then
  exit ${ls_ret}
elif [[ "$1" == "update" && "$update_done" == "1" ]] ; then
  echo ""
  $0 list
fi
exit 0
