#!/bin/bash
VERSION="0.1.1"

list="
addapps;additional-apps;$VERSION;--version;https://mde.gate-7.de/addapps/addapps
selfextractor;selfextractor;0.0.2;--version;https://mde.gate-7.de/addapps/selfextractor
sshenc;ssh-encryption;0.0.0;--version;https://mde.gate-7.de/addapps/sshenc
stc;syncthing CLI;;;https://github.com/tenox7/stc/releases/download/1.4/stc-amd64-linux
difft;difftastic;0.48.0;--version;https://github.com/Wilfred/difftastic/releases/download/<VERSION>/difft-x86_64-unknown-linux-gnu.tar.gz
drone;drone CLI;1.7.0;--version;https://github.com/harness/drone-cli/releases/download/v<VERSION>/drone_linux_amd64.tar.gz
"

_install() {
  name="$1"
  url="$2"

  FI=$(mktemp)
  wget -q -O $FI $url
  if [ -f /usr/local/bin/$name ] ; then
    sudo cp -f /usr/local/bin/$name /usr/local/bin/$name.backup
  fi
  sudo rm -f /usr/local/bin/$name
  if [[ $url == *".tar.gz" ]] ; then
    sudo tar -C /usr/local/bin/ -xzvf $FI
  else
    sudo cp $FI /usr/local/bin/$name
  fi
  sudo chmod 755 /usr/local/bin/$name
  sudo chown root:root /usr/local/bin/$name
  rm $FI
}
_remove() {
  name="$1"
  sudo cp -f /usr/local/bin/$name /usr/local/bin/$name.backup
  sudo rm -f /usr/local/bin/$name
}


show_help() {
  if [ "$1" = "" ] ; then
    echo ""
    echo "usage: $(basename $0) [-v|--version|-h|--help] refresh|update|list|install|remove <app_name>"
    echo ""
    exit 0
  fi
}

if [[ "$1" == "" ]] ; then
  show_help
  exit 0
fi

options=$(getopt -l "help,version" -o "hvp:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help) 
    show_help
    exit 0
    ;;
  -v|--version) 
    echo "$VERSION"
    exit 0
    ;;
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done

echo "$list" | while read -r i ; do

  name=$( echo "$i" | cut -d";" -f1)
  bez=$(  echo "$i" | cut -d";" -f2)
  ver=$(  echo "$i" | cut -d";" -f3)
  ver_cmd=$(  echo "$i" | cut -d";" -f4)
  url=$(  echo "$i" | cut -d";" -f5 | sed -e "s/<VERSION>/$ver/g" )
  if [ "$name" = "" ] ; then continue ; fi
  state="-"
  if [ -e /usr/local/bin/$name ] ; then
    state="o"
  fi
  version=""
  if [ "$ver_cmd" != "" ] ; then
    version=$( /usr/local/bin/$name $ver_cmd 2>/dev/null | grep -o '[0-9,.]*' )
    if [[ "$version" != "" && "$version" != "$ver" ]] ; then
      state="!"
    fi
  fi
  if [[ "$1" == "list" ]] ; then
    printf "%-1s %-15s %-8s %-8s %-20s # %s\n" "$state" "$name" "$version" "$ver" "$bez" "$url"
  fi
  if [[ "$1" == "refresh" && "$name" == "addapps"  ]] ; then
    _install "$name" "$url"
    exit
  fi
  if [[ "$1" == "install" && "$2" == "$name" ]] ; then
    _install "$name" "$url"
    exit 0
  fi
  if [[ "$1" == "remove" && "$2" == "$name" ]] ; then
    _remove "$name"
    exit 0
  fi

done

