#!/bin/bash

# remember to call "./addapps .getver" after version modifications!
VERSION="0.2.0"
IAM="crypter"

CFG_DIR="${HOME}/.config/${IAM}"

if ! command -v gocryptfs &> /dev/null
then
    echo "error: gocryptfs could not be found. Install it with: 'sudo apt-get install -y gocryptfs'"
    exit 1
fi

show_help()
{
  echo ""
  echo "# usage: `basename $0` <area> init|vi|mount|umount|info|passwd|mpoint"
  echo ""
  echo "# example with a \"test\" environment"
  echo ""
  echo "`basename $0` test init   # create gocryptfs AREA=test"
  echo "`basename $0` test vi     # modify mount/unmount settings"
  echo "`basename $0` test mount  # mount decrypted"
  echo "`basename $0` test umount # unmount decrypted"
  echo "`basename $0` test info   # show config and state"
  echo "`basename $0` test passwd # change password"
  echo "`basename $0` test mpoint # returns decrypted endpoint"
    echo ""
  echo "# configurations:"
  echo ""
  echo "  ${CFG_DIR}/<AREA>.conf"
  echo ""
  echo ""
}

if [ "$2" = "" ] ; then
  show_help
  exit 0
fi

options=$(getopt -l "help,version" -o "hvp:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help) 
    show_help
    exit 0
    ;;
  -v|--version) 
    echo "$VERSION"
    exit 0
    ;;
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done

AREA="$1"
CMD="$2"

if [[ "$CMD" = "init"  && ! -f ${CFG_DIR}/${AREA}.conf ]] ; then
  echo "# Crypter area \"${AREA}\" definition not yet defined."
  mkdir -p ${CFG_DIR}
  echo 'CRYPTER_CLEAR_DIR="~/'"${AREA}"'"'   >> ${CFG_DIR}/${AREA}.conf
  echo 'CRYPTER_SECRET_DIR="~/.'"${AREA}"'"' >> ${CFG_DIR}/${AREA}.conf
  echo 'CRYPTER_IDLE_TIMEOUT="10m"'       >> ${CFG_DIR}/${AREA}.conf
  echo "# Create template file:  ${CFG_DIR}/${AREA}.conf"
  echo "# Modify it with:"
  echo "$IAM $AREA vi"
  echo "# and re-call init"
  echo "$IAM $AREA init"
  echo ""
  exit 0
fi 
eval $(cat ${CFG_DIR}/${AREA}.conf | sed -e "s|~|${HOME}|g" )

if [ "$CMD" = "info" ] ; then
  echo ""
  echo "AREA=$AREA"
  echo ""
  echo "crypter config file <${CFG_DIR}/${AREA}.conf> :"
  cat ${CFG_DIR}/${AREA}.conf
  echo ""
  echo "gocryptfs config file <${CFG_DIR}/${AREA}-crypt.conf>"
  echo ""
  if [ -f ${CRYPTER_CLEAR_DIR}/${IAM}.log ] ; then
    echo "<${CRYPTER_SECRET_DIR}> is mounted to <${CRYPTER_CLEAR_DIR}>"
  else
    echo "<${CRYPTER_SECRET_DIR}> is not mounted to <${CRYPTER_CLEAR_DIR}>"
  fi
  echo ""
fi
if [[ "$CMD" = "mpoint" && -f ${CRYPTER_CLEAR_DIR}/${IAM}.log ]] ; then
    echo "${CRYPTER_CLEAR_DIR}"
fi

if [ "$CMD" = "init" ] ; then
  echo "establish gocryptfs config for $AREA"
  mkdir -p ${CRYPTER_SECRET_DIR} ${CRYPTER_CLEAR_DIR}
  gocryptfs -init -config ${CFG_DIR}/${AREA}-crypt.conf ${CRYPTER_SECRET_DIR}
  ret=$?
  if [ "$ret" != "0" ] ; then
    echo "error: on init gorypt, error=$ret"
    exit 1
  fi
  echo ""
  echo "or:"
  echo "$IAM $AREA mount"
  echo ""
fi
if [ "$CMD" = "passwd" ] ; then
  gocryptfs -passwd  -config ${CFG_DIR}/${AREA}-crypt.conf ${CRYPTER_SECRET_DIR}
fi 
if [ "$CMD" = "vi" ] ; then
  vi ${CFG_DIR}/${AREA}.conf
fi
if [ "$CMD" = "mount" ] ; then
  if [ -f ${CRYPTER_CLEAR_DIR}/${IAM}.log ] ; then
    echo "error: ${CRYPTER_CLEAR_DIR} still mounted!"
    exit 1
  fi
  gocryptfs -i ${CRYPTER_IDLE_TIMEOUT} -config ${CFG_DIR}/${AREA}-crypt.conf ${CRYPTER_SECRET_DIR} ${CRYPTER_CLEAR_DIR}
  ret=$?
  if [ "$ret" != "0" ] ; then
    echo "error: on mounting error=$ret"
    exit 1
  fi
  if [ ! -f ${CRYPTER_CLEAR_DIR}/${IAM}.log ] ; then
    echo "init   $( date +'%Y-%m-%d %H:%M:%S' ) ${USER}@$(hostname)" > ${CRYPTER_CLEAR_DIR}/${IAM}.log
  fi
  log="mount  $( date +'%Y-%m-%d %H:%M:%S' ) ${USER}@$(hostname)"
  sed -i "1s/^/${log}\n/" ${CRYPTER_CLEAR_DIR}/${IAM}.log
fi

if [ "$CMD" = "umount" ] ; then
  if [ ! -f ${CRYPTER_CLEAR_DIR}/${IAM}.log ] ; then
    echo "error: ${CRYPTER_CLEAR_DIR} not mounted!"
    exit 1
  fi
  log="umount $( date +'%Y-%m-%d %H:%M:%S' ) ${USER}@$(hostname)"
  sed -i "1s/^/${log}\n/" ${CRYPTER_CLEAR_DIR}/${IAM}.log
  fusermount -u ${CRYPTER_CLEAR_DIR}
  if [ -f ${CRYPTER_CLEAR_DIR}/${IAM}.log ] ; then
    echo "error unmounting ${CRYPTER_CLEAR_DIR}"
    exit 1
  fi
fi
exit 0
