#!/bin/bash

show_help()
{
  echo ""
  echo "usage: `basename $0` <content-directory> [selfextractor-file]"
  echo ""
  echo "example:"
  echo ""
  echo "`basename $0` ./hugo  # create directory and a template installer script."
  echo ""
  echo "# copy desired content to the ./hugo directory and modify installer script:"
  echo "vi ./hugo/installer"
  echo ""
  echo "`basename $0` ./hugo # re-create installable selfextractor file: ./hugo.sh"
  echo "#or:"
  echo "`basename $0` ./hugo /tmp/my-selfextractor.sh"
  echo ""
}

if [ "$1" = "" ] ; then
  show_help
  exit 0
fi

options=$(getopt -l "help,version" -o "hvp:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help) 
    show_help
    exit 0
    ;;
  -v|--version)
    if [ -f /opt/dc/VERSION ] ; then
      cat /opt/dc/VERSION
    else
      echo ""
    fi
    exit 0
    ;;
  
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done
if [ "$1" = "remove" ] ; then
  echo "calling $1"
fi

if [ "$1" = "install" ] ; then
  if [ -f /opt/dc/VERSION ] ; then
    # dc already installed
    (cd /opt/dc ; git pull)
    dc install
  else
    git clone https://github.com/unimock/dc.git /opt/dc
    /opt/dc/bin/dc-install --force
    /opt/dc/helper/install/docker
  fi
fi
exit 0
