#!/bin/bash
# remember to call "./addapps .getver" after version modifications!
VERSION="0.0.1"

IAM=`basename $0`


show_help() {
  echo "# usage: $IAM list|update"
  echo ""
  echo "# examples:"
  echo ""
  echo "$IAM list              # list used images and their states"
  echo ""
  echo "$IAM update /root/dc/apps/ecf/zigbee  koenkk/zigbee2mqtt:2.1.1"
  echo ""
} 

if [ "$1" = "" ] ; then
  show_help
  exit 0
fi

options=$(getopt -l "help,version" -o "hvp:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help)
    show_help
    exit 0
    ;;
  -v|--version)
    echo "$VERSION"
    exit 0
    ;;
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done

update_list="
#general
traefik:v3.3.3
#ecf:
smeagolworms4/mqtt-explorer:browser-1.0.3
homeassistant/home-assistant:2024.12
unimock/ow-mqtt:0.1.0
zavy86/wikidocs:1.0.74
grafana/grafana:11.5.2
gitea/gitea:1.23.4
kanboard/kanboard:v1.2.43
nodered/node-red:4.0.9
koenkk/zigbee2mqtt:2.1.1
influxdb:2.7.11-alpine
mneundorfer/owserver:1.1
legobas/mqtt-timer:1.24.0
eclipse-mosquitto:2.0.20
unimock/rfid-mqtt-docker:0.0.1
"

if [ "$1" = "list" ] ; then
  #
  # create information arrays
  #
  env_list=$(find ${MDE_DC_APP_DIR} -type f -name .env)
  idx=0
  for env in $env_list ; do
    state[$idx]=" "
    image=$(grep "^DC_ENV_IMAGE=" $env | sed "s|^DC_ENV_IMAGE=||g")
    img_name[$idx]=${image%:*}
    img_ver[$idx]=${image#*:}
    for u in $update_list ; do
      u_name=${u%:*}
      u_ver[$idx]=${u#*:}
      if [ "${u_name}" = "${img_name[$idx]}" ] ; then
        if [ "${u_ver[$idx]}" = "${img_ver[$idx]}" ] ; then
          state[$idx]="o"
        else
          state[$idx]="!"
        fi
        break
      fi
    done
    dname[$idx]=$(dirname $env )
    let idx=$idx+1
  done
  #
  # print informations
  #
  found="0"
  for (( idx=0; idx < ${#state[@]}; idx++ )) ; do
    dstate="☐"
    if [ "${state[$idx]}" = "o" ] ; then
      dstate="✅"
    elif  [ "${state[$idx]}" = "!" ] ; then
      dstate="💡"
    fi	  
    if [ "${state[$idx]}" = "!" ] ; then
      printf "%-1s %-2d %-34s %-30s %-20s %-20s\n" "${dstate}" "$idx" "${dname[$idx]}" "${img_name[$idx]}" "${img_ver[$idx]}" "${u_ver[$idx]}"
      found="1"
    else
      printf "%-1s %-2d %-34s %-30s %-20s\n"       "${dstate}" "$idx" "${dname[$idx]}" "${img_name[$idx]}" "${img_ver[$idx]}"
    fi
  done
  if [ "${found}" = "1" ] ; then
  #
  # print update commands
  #
  printf "\n\n"
  for (( idx=0; idx < ${#state[@]}; idx++ )) ; do
    if [ "${state[$idx]}" = "!" ] ; then
      printf "%s update %-34s %s:%s\n" "$IAM" "${dname[$idx]}" "${img_name[$idx]}" "${u_ver[$idx]}"
    fi
  done
  printf "\n\n"
  fi
fi

if [ "${1}" = "update" ] ; then
  ( cd ${2} ; dc docker pull ${3} )
  sed -i "s|^DC_ENV_IMAGE=.*|DC_ENV_IMAGE=${3}|g" ${2}/.env
  ( cd ${2} ; dc rmup )
fi

exit 0
