#!/bin/bash
# remember to call "./addapps .getver" after version modifications!
VERSION="0.3.0"


show_help() {
  MD_FILE="./new-file.md"
  if [ "$1" != "" ] ; then
    MD_FILE="$1"
  fi
  echo ""
  echo "# usage: $(basename $0) <md-file> show|list|run|create [section] [-o <var>=<val>].."
  echo ""
  echo ""
  echo "# example:"
  echo ""
  echo "`basename $0` ${MD_FILE} list        # list available sections"
  echo "`basename $0` ${MD_FILE} run         # execute sections"
  echo "`basename $0` ${MD_FILE} show        # show relevant content"
  echo "`basename $0` ${MD_FILE} create      # create template md file"
  echo ""
  echo ""
  echo "`basename $0` ${MD_FILE} run          # execute all sections"
  echo "`basename $0` ${MD_FILE} run  create  # execute 'create' section"
  echo "`basename $0` ${MD_FILE} run  test    # execute 'test'   section"
  echo "`basename $0` ${MD_FILE} run  delete  # execute 'delete' section"
  echo "`basename $0` ${MD_FILE} dump create  # dump 'create' section"
  echo "`basename $0` ${MD_FILE} dump test    # dump 'test'   section"
  echo "`basename $0` ${MD_FILE} dump delete  # dump 'delete' section"
  echo ""
  echo "# overwrite variable values:"
  echo ""
  echo "`basename $0` ${MD_FILE} run                   # use values from md-file"
  echo "`basename $0` ${MD_FILE} run -o X=\"new value\"  # overwrite value"
  echo ""
  echo ""
}

declare -A opt_args

####################################################################################
# magic main
####################################################################################
options=$(getopt -l "help,version,overwrite" -o "hvo:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help)
    show_help
    exit 0
    ;;
  -v|--version)
    echo "$VERSION"
    exit 0
    ;;
  -o|--overwrite)
    opt_args+=($2)
    ;;
  --)
    shift
    break;;
  esac
  shift
done

#echo "$@"


if [ "$1" = "" ] ; then
  show_help
  exit 0
fi
if [ "$2" = "" ] ; then
  show_help "$1"
  exit 0
fi


FI="$1"
if [ "$2" = "create" ] ; then
  if [ -f $FI ] ; then
    echo "error: file already exist"
    exit 1
  fi
  cat >$FI <<EOF
# md-exec template

[//]: # (md-exec: global)
\`\`\`global
X="my_global_var"
echo "set global variables"
\`\`\`

[//]: # (md-exec: create test env)
\`\`\`create
echo "execute create with X=\$X"
\`\`\`

[//]: # (md-exec: execute test)
\`\`\`test
echo "execute test with X=\$X"
\`\`\`

[//]: # (md-exec: delete test env)
\`\`\`delete
echo "execute delete with X=\$X"
\`\`\`
EOF
  echo ""
  echo "$FI created"
  echo ""
  exit 0
fi
  
if [ "$FI" = "" -o ! -f "$FI" ] ; then
  echo "error: file <$FI> does not exist!"
  exit 1
fi
CMD="$2"
if [ "$CMD" != "run" -a "$CMD" != "show" -a "$CMD" != "list" -a "$CMD" != "dump"  ] ; then
  echo "error unkown command given"
  exit 1
fi
TAG="$3"

script=$(mktemp)

ret=0
if [ "$TAG" = "" ] ; then
  if [ "$CMD" = "show" ] ; then
    cat $FI | sed  -n '/```/,/```/p'                    | sed 's/ *$//g' | sed '/^$/d'                    > $script
  elif [ "$CMD" = "list" ] ; then
    cat $FI | grep "\`\`\`.*" | sed 's|```||g' | sed 's/ *$//g' | sed '/^$/d'                 > $script
  else
    cat $FI | sed  -n '/```/,/```/p' | sed 's/```.*//g' | sed 's/ *$//g' | sed '/^$/d'                    > $script
  fi
else
  if [ "$CMD" = "show" ] ; then
    cat $FI | sed  -n '/```global$\|```'$TAG'$/,/```/p'                    | sed 's/ *$//g' | sed '/^$/d'  > $script
  elif [ "$CMD" = "dump" ] ; then
    cat $FI | sed  -n '/```'$TAG'$/,/```/p' | sed '/```.*/d'     > $script
  else 
    cat $FI | sed  -n '/```global$\|```'$TAG'$/,/```/p' | sed 's/```.*//g' | sed 's/ *$//g' | sed '/^$/d'  > $script
  fi
fi
for arg in "${!opt_args[@]}" ; do
  var=${arg%=*}
  val=${arg#*=}
  sed -i "/^[[:blank:]]*${var}=*/c\\${var}=\"${val}\"" $script
done

if [ "$CMD" = "list" -o "$CMD" = "show" -o "$CMD" = "dump" ] ; then
  cat $script | envsubst
fi
if [ "$CMD" = "run" ] ; then
  chmod a+x $script
  $script  
  ret=$?
fi
rm $script
exit $ret
