#!/bin/bash

# remember to call "./addapps .getver" after version modifications!
VERSION="0.0.2"

show_help()
{
  echo ""
  echo "usage: `basename $0` <content-directory> [selfextractor-file]"
  echo ""
  echo "example:"
  echo ""
  echo "`basename $0` ./hugo  # create directory and a template installer script."
  echo ""
  echo "# copy desired content to the ./hugo directory and modify installer script:"
  echo "vi ./hugo/installer"
  echo ""
  echo "`basename $0` ./hugo # re-create installable selfextractor file: ./hugo.sh"
  echo "#or:"
  echo "`basename $0` ./hugo /tmp/my-selfextractor.sh"
  echo ""
}

if [ "$1" = "" ] ; then
  show_help
  exit 0
fi

options=$(getopt -l "help,version" -o "hvp:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help) 
    show_help
    exit 0
    ;;
  -v|--version) 
    echo "$VERSION"
    exit 0
    ;;
  
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done
if [ "$1" = "remove" ] ; then
  echo "calling $1"
  apt-get purge -y mde-base
  rm -f /etc/apt/sources.list.d/mde.list*
fi

if [ "$1" = "install" ] ; then
  echo "calling $1"
  mkdir -p /etc/apt/keyrings/
  wget -O - http://mde.gate-7.de/apt/g7-apt-key | gpg --dearmor -o /etc/apt/keyrings/mde.gpg
  echo  "deb [signed-by=/etc/apt/keyrings/mde.gpg] https://mde.gate-7.de/apt mde main" >/etc/apt/sources.list.d/mde.list
  apt-get update
  apt-get install -y mde-base
fi
exit 0
