#!/bin/bash
# remember to call "./addapps .getver" after version modifications!
VERSION="0.0.0"
IAM="stsync"

####################################################################################
check_dependencies() {
  local missing=0
  local addapps="crypter stc"
  local aptpkg=""
  local list="$addapps $aptpkg"
  addapps=" $addapps "
  for i in $list ; do
    if ! command -v $i &> /dev/null ; then
      missing=1  
      if [[ $addapps == *" $i "* ]]; then
         echo "error: $i could not be found. Install it with: addapps install $i"
      else
         echo "error: $i could not be found. Install it with: sudo apt-get install -y $i"
      fi
    fi
  done
  if [ "$missing" = "1" ] ; then
    exit 1
  fi
}
####################################################################################
show_help()
{
  echo ""
  echo "usage: $IAM init|list|create|read"
  echo ""
  echo "example:"
  echo ""
  echo "$IAM ./hugo  # create directory and a template installer script."
  echo ""
  echo "# copy desired content to the ./hugo directory and modify installer script:"
  echo "vi ./hugo/installer"
  echo ""
  echo "$IAM ./hugo # re-create installable selfextractor file: ./hugo.sh"
  echo "#or:"
  echo "$IAM ./hugo /tmp/my-selfextractor.sh"
  echo ""
}

####################################################################################
# magic main
####################################################################################


options=$(getopt -l "help,version" -o "hvp:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help) 
    show_help
    exit 0
    ;;
  -v|--version) 
    echo "$VERSION"
    exit 0
    ;;
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done

if [ "$1" = "" ] ; then
  show_help
  exit 0
fi

check_dependencies

source /usr/local/include/addapps.funcs

# assign /Docker/...
# para:
# stc direkt
# check syncting is running
# rescan 
# check peer host status und 100%
ST
STSYSYNC_HOST="vms.mok.intra"
STSYSYNC_DIR="Micha"

ST_OPT="--homedir /Docker/Services/syncthing/service"


exit 0

