#!/bin/bash
# remember to call "./addapps .getver" after version modifications!
VERSION="0.0.3"
IAM="stsync"

####################################################################################
check_dependencies() {
  local missing=0
  local addapps="stc"
  local aptpkg=""
  local list="$addapps $aptpkg"
  addapps=" $addapps "
  for i in $list ; do
    if ! command -v $i &> /dev/null ; then
      missing=1  
      if [[ $addapps == *" $i "* ]] ; then
         echo "error: $i could not be found. Install it with: addapps install $i"
      else
         echo "error: $i could not be found. Install it with: sudo apt-get install -y $i"
      fi
    fi
  done
  if [ "$missing" = "1" ] ; then
    exit 1
  fi
}
####################################################################################
show_help()
{
  echo ""
  echo "usage: $IAM init|list|create|read"
  echo ""
  echo "example:"
  echo ""
  echo "$IAM stc [<stc-commands>]   # call stc"
  echo "$IAM stc help               # show stc-commands"
  echo "$IAM device [<device-name>] #"
  echo "$IAM folder [<folder-name>] #"
  echo ""
}

####################################################################################
# magic main
####################################################################################


options=$(getopt -l "help,version" -o "hvp:" -a -- "$@")
eval set -- "$options"
while true ; do
  case "$1" in
  -h|--help) 
    show_help
    exit 0
    ;;
  -v|--version) 
    echo "$VERSION"
    exit 0
    ;;
  -p)
    shift
    xxxxx="$1"
    ;;
  --)
    shift
    break;;
  esac
  shift
done

if [ "$1" = "" ] ; then
  show_help
  exit 0
fi

check_dependencies

source /usr/local/include/addapps.funcs

# assign /Docker/...
# para:
# check syncting is running
# rescan 
# check peer host status und 100%
SYNC_PEER="vms.mok.intra"
SYNC_DIR="Micha"
SYNC_ST_OPT="--homedir /Docker/Services/syncthing/service"

CMD="$1"
shift
if [ "$CMD" = "stc" ] ; then
  if [ "$1" = "help" ] ; then
    stc $SYNC_ST_OPT --help
    ret=$?
  else
    stc $SYNC_ST_OPT $*
    ret=$?
  fi
  exit $ret
fi
if [ "$CMD" = "folder" ] ; then
  pat="$1"
  shift
  list=$(stc $SYNC_ST_OPT stc | awk '/^Folder/{flag=1; next} /^Device/{flag=0} flag' | sed '/^[[:space:]]*$/d')
  if [ "$pat" != "" ] ; then
    echo "$list" | grep -E "^$pat |^\*$pat" 2>/dev/null | sed "s|^\*||g" | awk '{ print $2 " " $3}' | sed "s|%||g"
  else
    echo "$list"  
  fi
fi
if [ "$CMD" = "device" ] ; then
  pat="$1"
  shift
  list=$(stc $SYNC_ST_OPT stc | awk '/^Device/{flag=1; next} /^XXXX/{flag=0} flag' | sed '/^[[:space:]]*$/d')
  if [ "$pat" != "" ] ; then
    echo "$list" | grep -E "^$pat |^\*$pat" 2>/dev/null | sed "s|^\*||g" | sed "s| Myself | OK |g" | awk '{ print $2 " " $3}' | sed "s|%||g"
  else
    echo "$list"  
  fi
fi
exit 0

