#!/bin/bash
error_detect=0
err_report() { echo "Error on line $1" ; error_detect=1 ; } ; trap 'err_report $LINENO' ERR
################################################################################
# dc-hcloud context create  dc  # creates: ~/.config/hcloud/cli.toml 
# dc-hcloud ssh-key create --name dc --public-key-from-file dc/hosts/id_ed25519.pub
################################################################################
source ${HOME}/.dc/etc/config
HOST="test"

dc host    $HOST config  create test.intra sshd    # create new host definition with hostname test.intra and type "dc"
  VSERVER="test" ; TEMPL="kvm"
  dc host    $HOST vserver assign $VSERVER $TEMPL  # assign virtual server to host
  dc host    $HOST vserver create                  # create assigned hetzner cloud server
  ssh $HOST hostname ; ssh $HOST uptime
  dc host    $HOST vserver delete                  # delete assigned virtual server
  VSERVER="test@kvm1" ; TEMPL="kvm1"
  dc host    $HOST vserver assign $VSERVER $TEMPL  # assign virtual server to host
  dc host    $HOST vserver create                  # create assigned hetzner cloud server
  ssh $HOST hostname ; ssh $HOST uptime
  dc host    $HOST vserver delete                  # delete assigned virtual server
  #VSERVER="test" ; TEMPL="hcloud"
  #dc host    $HOST vserver assign $VSERVER $TEMPL # assign virtual server to host
  #dc host    $HOST vserver create                 # create assigned hetzner cloud server
  #ssh $HOST hostname ; ssh $HOST uptime
dc host    $HOST config  delete                    # delete host definition
echo "error_detect=$error_detect"
exit $error_detect

